################################### Default Configuration ############################
baseurl = "https://biocodellc.com/"
languageCode = "en"
title = "Biocode, LLC"
theme = "vex"

#################################### Plugins ##########################################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "https://fonts.googleapis.com/css?family=Droid+Serif:400i|Source+Sans+Pro:300,400,600,700"
  [[params.plugins.css]]
  URL = "https://fonts.googleapis.com/css?family=Josefin+Sans:300,400,600,700"
  [[params.plugins.css]]
  URL = "css/bootstrap.min.css"
  [[params.plugins.css]]
  URL = "css/themefisher-fonts.css"
  [[params.plugins.css]]
  URL = "css/owl.carousel.css"
  [[params.plugins.css]]
  URL = "css/magnific-popup.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "js/jquery-2.1.1.min.js"
  [[params.plugins.js]]
  URL = "js/bootstrap.min.js"
  [[params.plugins.js]]
  URL = "js/owl.carousel.min.js"
  [[params.plugins.js]]
  URL = "js/jquery.magnific-popup.min.js"


###################################### Navigation ######################################
[menu]
    
[[menu.main]]
  name = "Technology"
  URL = "aboutFlexibleData"
  weight = 1

  [[menu.main]]
  name = "The Team"
  URL = "aboutus"
  weight = 2

  [[menu.main]]
  name = "Current Projects"
  URL = "currentprojects"
  weight = 3

[build]
publish = "public"
command = "hugo --gc --minify"

[build.environment]
  HUGO_VERSION = "0.66.0"

[context.production.environment]
HUGO_VERSION = "0.66.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.66.0"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.66.0"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.66.0"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"